export const SHOW_INPUT_FORM = "SHOW_INPUT_FORM";
export const CLOSE_INPUT_FORM = "CLOSE_INPUT_FORM";
export const FETCH_ACCOUNT_LIST = "FETCH_ACCOUNT_LIST";

export const FETCH_DEPARTMENT_LIST = "FETCH_DEPARTMENT_LIST";
export const FETCH_POSITION_LIST = "FETCH_POSITION_LIST";
